name: linting-test-coverage
on: [pull_request_target]

env:
  PYTHON_VER: "3.12"
  DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Install black
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Python linting
        run: |
          poetry run black .
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Install dependancies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Python unit tests
        run: |
          poetry run coverage run -m unittest
          poetry run coverage xml
      - name: Test coverage to deepsource.io
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
