name: linting-test-coverage
on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v1
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
